#!/usr/bin/env bash
set -euo pipefail

# Embed SPA dist into a generated TypeScript module.
# The SPA is tar-gzipped and base64-encoded as a string constant.
# At runtime, spa-resolve.ts extracts it to ~/.mecha/.spa-cache/<version>/
#
# Usage: ./scripts/embed-spa.sh

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SPA_DIST="$ROOT/packages/spa/dist"
OUTPUT="$ROOT/packages/cli/src/spa-embedded.generated.ts"
VERSION=$(node -e "process.stdout.write(require(process.argv[1]).version)" "$ROOT/package.json")

if [[ ! -d "$SPA_DIST" ]] || [[ ! -f "$SPA_DIST/index.html" ]]; then
  echo "Error: SPA not built. Run: pnpm --filter @mecha/spa build" >&2
  exit 1
fi

# Validate target arg before doing expensive work
REQUESTED="${1:-embed}"
if [[ "$REQUESTED" != "embed" ]]; then
  echo "Usage: $0" >&2
  exit 1
fi

echo "Embedding SPA dist ($SPA_DIST)..."

# Create tar.gz of spa/dist contents, base64 encode without line wrapping
ARCHIVE=$(tar -czf - -C "$SPA_DIST" . | base64 | tr -d '\n')

# Count files and size
FILE_COUNT=$(find "$SPA_DIST" -type f | wc -l | tr -d ' ')
RAW_SIZE=$(du -sh "$SPA_DIST" | awk '{print $1}')
ARCHIVE_SIZE=${#ARCHIVE}
ARCHIVE_KB=$((ARCHIVE_SIZE / 1024))

# Write to temp file then atomic mv to prevent truncated output on interruption
TMP_OUTPUT="${OUTPUT}.tmp.$$"
trap 'rm -f "$TMP_OUTPUT"' EXIT

cat > "$TMP_OUTPUT" << TYPESCRIPT
// AUTO-GENERATED by scripts/embed-spa.sh — do not edit
// $FILE_COUNT files, $RAW_SIZE raw, ${ARCHIVE_KB}KB compressed+base64
/* v8 ignore start */
/* eslint-disable */
export const SPA_ARCHIVE_B64 = "${ARCHIVE}";
export const SPA_VERSION = "${VERSION}";
/* v8 ignore stop */
TYPESCRIPT

mv "$TMP_OUTPUT" "$OUTPUT"

echo "  → $OUTPUT"
echo "  → $FILE_COUNT files, $RAW_SIZE raw, ${ARCHIVE_KB}KB embedded"
