baseURL = 'https://mecha.im/'
languageCode = 'en-us'
title = 'Mecha'
publishDir = '../website'
enableEmoji = true

[build]
  noJSConfigInAssets = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.140.0"
  [[module.imports]]
    path = "github.com/colinwilson/lotusdocs"
    disable = false
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    disable = false

[markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

[params]
  google_fonts = [
    ["Inter", "300, 400, 600, 700"],
    ["Fira Code", "500, 700"]
  ]
  sans_serif_font = "Inter"
  secondary_font  = "Inter"
  mono_font       = "Fira Code"

  [params.footer]
    copyright = "© :YEAR: [Mecha](https://mecha.im). Built with [**Lotus Docs**](https://github.com/colinwilson/lotusdocs)"
    version   = false

  [params.social]
    github = "xiaolai/mecha.im"

  [params.docs]
    title           = "Mecha"
    themeColor      = "terracotta"
    darkMode        = true
    prism           = true
    repoURL         = "https://github.com/xiaolai/mecha.im"
    repoBranch      = "main"
    editPage        = true
    lastMod         = false
    toc             = true
    tocMobile       = true
    scrollSpy       = true
    sidebarIcons    = true
    titleIcon       = true
    breadcrumbs     = true
    navDesc         = true
    navDescTrunc    = 30
    listDescTrunc   = 100
    backToTop       = true
    descriptions    = true
    intLinkTooltip  = true
    logoLinkURL     = "/"

  [params.flexsearch]
    enabled = true

[[menu.primary]]
  name  = "Docs"
  url = "/docs/"
  identifier = "docs"
  weight = 10
